- name: My Task
  hosts: home_servers
  remote_user: ansible
  tasks:
    - name: Create code directory
      file:
        path: ~/code
        state: directory
        mode: '0755'
         
    - name: Copy flask-home
      synchronize:
        src: "{{ WORKSPACE }}/flask-home/"
        dest: "~/code/flask-home/"
        
    - name: Copy flask-ml
      synchronize:
        src: "{{ WORKSPACE }}/flask-ml/"
        dest: "~/code/flask-ml/"
            
    - name: Deploy code
      include: deploy_code.yml